---
#Inlined from scab ci/tasks/acceptance-tests.yml with ((docker-registry-url)) appended to openjdk
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((docker-registry-url))openjdk
    tag: 8

inputs:
  - name: git-repo  # java sources to build
  - name: ci-repo   # where the script is loaded from
  - name: metadata  # concourse meta-data resource made available in task
outputs:
  - name: git-repo  # resulting build artefacts

# Cache gradle dependencies across executions
# https://concourse-ci.org/tasks.html#schema.task.caches
# Those are symlinked to ~/.gradle and ~/.m2
caches:
  - path: maven
  - path: gradle

run:
  path: ci-repo/scripts/acceptance-tests.sh

params:
  EXPOSE_PROD_ENV_VARS: # when set to "true", then the prod env vars are exposed. Required for testing prod environment startup
  EXPOSE_AT_ENV_VARS:   # when set to "true", then the acceptance test env vars are exposed. Required for launching SCAB AT.
  API_HOST:
  API_PORT:
  USERNAME:
  PASSWORD:
  CLIENT_ID:
  CLIENT_SECRET:
  DEFAULT_ORG:
  DEFAULT_SPACE:
  SKIP_SSL_VALIDATION:
    # gradlew arguments and target after http proxy configuration.
  GRADLE_ARGS:
  ARTIFACTORY_URL: # url without a leading slash
