---
#Inlined from scab ci/tasks/acceptance-tests.yml with ((docker-registry-url)) appended to openjdk
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((docker-registry-url))openjdk
    tag: 8

inputs:
  - name: git-repo  # java sources to build
  - name: ci-repo   # where the script is loaded from
# Cache gradle dependencies across executions
# https://concourse-ci.org/tasks.html#schema.task.caches
# Those are symlinked to ~/.gradle and ~/.m2
caches:
  - path: maven
  - path: gradle

run:
  path: ci-repo/scripts/acceptance-tests.sh

params:
  API_HOST:
  API_PORT:
  USERNAME:
  PASSWORD:
  CLIENT_ID:
  CLIENT_SECRET:
  DEFAULT_ORG:
  DEFAULT_SPACE:
  SKIP_SSL_VALIDATION:
    # gradlew arguments and target after http proxy configuration.
  GRADLE_ARGS:
