---
#Inlined from scab ci/tasks/acceptance-tests.yml with ((docker-registry-url)) appended to openjdk
platform: linux

#Inspired by COA
image_resource:
  type: docker-image
  source:
    repository: ((docker-registry-url))governmentpaas/cf-cli
    tag: 2857fdbaea59594c06cf9c6e32027091b67d4767

inputs:
  - name: ci-repo   # where the script is loaded from

run:
  path: ci-repo/scripts/clean-at-cf-environment.sh

params:
  API_HOST:
  API_PORT:
  USERNAME:
  PASSWORD:
  DEFAULT_ORG:
  DEFAULT_SPACE:
  SKIP_SSL_VALIDATION:
